def elastest_url = ''
node('et_in_et'){
    elastest(tss: ['EUS'], surefireReportsPattern: '**/target/surefire-reports/TEST-*.xml', project: 'ETinET', sut: 11) {
      stage ('docker container')
          sh 'env'
          def mycontainer = docker.image('elastest/ci-docker-e2e:latest')
          mycontainer.pull()
          mycontainer.inside("-u root -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {

            stage('setup container'){
                sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
                git credentialsId: '8831519f-233b-4147-ade9-676420a73eba', url: 'git@bitbucket.org:doylego/ere-v2a.git'
                elastest_url = env.ET_SUT_PROTOCOL + '://' + env.ET_SUT_HOST + ':' + env.ET_SUT_PORT
            }

            stage ('E2E tests'){
              echo ('E2E tests')
              try {
                sh "cd -; cd ere-e2e; mvn clean test -DskipTests=false -DetmUrl=" + elastest_url + " -DetmUsername=elastest -DetmPassword=3xp3r1m3nt47"
              } catch (e){
                  echo 'Error: ' + e.toString()
              } finally {
                 step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
              }
            }
          }
      }
  }
